// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.19.6
// source: messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "webload";

export interface Stats {
  cpuUsage: number;
  memMax: number;
  memUsed: number;
  memUsage: number;
  uptime: number;
}

export interface Id {
  id: number;
}

function createBaseStats(): Stats {
  return { cpuUsage: 0, memMax: 0, memUsed: 0, memUsage: 0, uptime: 0 };
}

export const Stats: MessageFns<Stats> = {
  encode(message: Stats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cpuUsage !== 0) {
      writer.uint32(13).float(message.cpuUsage);
    }
    if (message.memMax !== 0) {
      writer.uint32(16).uint64(message.memMax);
    }
    if (message.memUsed !== 0) {
      writer.uint32(24).uint64(message.memUsed);
    }
    if (message.memUsage !== 0) {
      writer.uint32(37).float(message.memUsage);
    }
    if (message.uptime !== 0) {
      writer.uint32(40).uint64(message.uptime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Stats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.cpuUsage = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.memMax = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.memUsed = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.memUsage = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.uptime = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Stats {
    return {
      cpuUsage: isSet(object.cpuUsage) ? globalThis.Number(object.cpuUsage) : 0,
      memMax: isSet(object.memMax) ? globalThis.Number(object.memMax) : 0,
      memUsed: isSet(object.memUsed) ? globalThis.Number(object.memUsed) : 0,
      memUsage: isSet(object.memUsage) ? globalThis.Number(object.memUsage) : 0,
      uptime: isSet(object.uptime) ? globalThis.Number(object.uptime) : 0,
    };
  },

  toJSON(message: Stats): unknown {
    const obj: any = {};
    if (message.cpuUsage !== 0) {
      obj.cpuUsage = message.cpuUsage;
    }
    if (message.memMax !== 0) {
      obj.memMax = Math.round(message.memMax);
    }
    if (message.memUsed !== 0) {
      obj.memUsed = Math.round(message.memUsed);
    }
    if (message.memUsage !== 0) {
      obj.memUsage = message.memUsage;
    }
    if (message.uptime !== 0) {
      obj.uptime = Math.round(message.uptime);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Stats>, I>>(base?: I): Stats {
    return Stats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Stats>, I>>(object: I): Stats {
    const message = createBaseStats();
    message.cpuUsage = object.cpuUsage ?? 0;
    message.memMax = object.memMax ?? 0;
    message.memUsed = object.memUsed ?? 0;
    message.memUsage = object.memUsage ?? 0;
    message.uptime = object.uptime ?? 0;
    return message;
  },
};

function createBaseId(): Id {
  return { id: 0 };
}

export const Id: MessageFns<Id> = {
  encode(message: Id, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Id {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Id {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: Id): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Id>, I>>(base?: I): Id {
    return Id.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Id>, I>>(object: I): Id {
    const message = createBaseId();
    message.id = object.id ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
